repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.20.0"
    hooks:
      - id: blacken-docs
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
      - id: reorder-python-imports
        args: ["--py314-plus"]
        exclude: "^tests/"
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.5
    hooks:
      - id: poetry-lock
        language_version: python3.14
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-type-checking
          - flake8-pyproject
          - flake8-tidy-imports
        args: ["--max-line-length=88"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: ["--py314-plus"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.7.0
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint
