name: Bump Version and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv and python
        uses: astral-sh/setup-uv@v7
      - name: Install Poetry
        run: |
          uv tool install "poetry==1.8.5"
      - name: Set version with Poetry
        run: poetry version ${{ github.ref_name }}
      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Bump version to ${{ github.ref_name }}"
          file_pattern: pyproject.toml poetry.lock
      - name: Build distribution
        run: poetry build
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*
