name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv and python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
      - name: Install Poetry
        run: uv tool install "poetry==1.8.5"
      - name: Verify tag matches poetry version
        run: |
          POETRY_VERSION=$(poetry version --short)
          TAG_VERSION=${GITHUB_REF_NAME#v}
          echo "Package version: $POETRY_VERSION"
          echo "Tag: $TAG_VERSION"
          if [ "$POETRY_VERSION" != "$TAG_VERSION" ]; then
            exit 1
          fi
      - name: Build distribution
        run: poetry build
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/*
