name: Run tox
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: linux-python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v5
      - name: Install uv and python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox and poetry
        run: |
          uv tool install tox --with tox-uv
          uv tool install "poetry==1.8.5"
      - name: Test with tox
        run: tox -vv -e ${{ matrix.python-version }}
